#!/usr/bin/env python3
"""
SkillsDB v3.0 Build & Bundler Script
Compiles the modular skillsdb/ Python package into a 100% backward-compatible,
standalone single-file script: database/db_manager.py.
"""

import re
import sys
from pathlib import Path

MODULE_ORDER = [
    "config.py",
    "core/db.py",
    "search/synonyms.py",
    "core/detector.py",
    "core/concurrency.py",
    "memory/writer_queue.py",
    "platform/windows_utf8.py",
    "search/fts.py",
    "memory/project_memory.py",
    "updater/merger.py",
    "cli.py",
]

HEADER = '''#!/usr/bin/env python3
"""
Antigravity Central Customizations, Autonomous Memory & Knowledge Engine
========================================================================
AUTO-GENERATED BY build.py FROM THE MODULAR skillsdb/ PACKAGE.
DO NOT EDIT THIS FILE DIRECTLY.
To make changes, edit the corresponding module in skillsdb/ and run:
    python build.py

Version: 3.0.0
"""

import os
import sys
import re
import json
import time
import queue
import shutil
import sqlite3
import argparse
import threading
import subprocess
import urllib.request
import concurrent.futures
from pathlib import Path
from datetime import datetime, timezone

if sys.platform == "win32":
    try:
        import winreg
    except ImportError:
        pass
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass
'''

def bundle():
    repo_root = Path(__file__).parent.resolve()
    pkg_dir = repo_root / "skillsdb"
    target_file = repo_root / "database" / "db_manager.py"

    print("=" * 60)
    print("SkillsDB Bundler: Compiling package into standalone db_manager.py")
    print(f"Source Package: {pkg_dir}")
    print(f"Target Output:  {target_file}")
    print("=" * 60)

    if not pkg_dir.exists():
        print(f"Error: {pkg_dir} does not exist.")
        sys.exit(1)

    bundled_chunks = [HEADER.strip()]

    for rel_path in MODULE_ORDER:
        module_path = pkg_dir / rel_path
        if not module_path.exists():
            print(f"Error: Required module file {module_path} not found.")
            sys.exit(1)

        print(f"  * Bundling: skillsdb/{rel_path}")
        content = module_path.read_text(encoding="utf-8")
        lines = content.splitlines()

        filtered_lines = []
        in_module_docstring = False
        docstring_done = False
        in_multiline_skip = False
        in_win_reconfig = False

        for idx, line in enumerate(lines):
            stripped = line.strip()

            # Handle multiline import skips
            if in_multiline_skip:
                if ")" in stripped:
                    in_multiline_skip = False
                continue

            # Strip leading module docstrings
            if not docstring_done:
                if stripped.startswith('"""') or stripped.startswith("'''"):
                    if (stripped.count('"""') >= 2 or stripped.count("'''") >= 2) and len(stripped) > 3:
                        docstring_done = True
                        continue
                    in_module_docstring = not in_module_docstring
                    if not in_module_docstring:
                        docstring_done = True
                    continue
                if in_module_docstring:
                    continue
                if not stripped:
                    continue
                docstring_done = True

            # Skip package-relative imports (from . or from ..)
            if re.match(r"^from\s+\.+", stripped):
                if "(" in stripped and ")" not in stripped:
                    in_multiline_skip = True
                continue

            # Skip standard library imports already in header
            if re.match(r"^(import|from)\s+(os|sys|re|json|time|queue|shutil|sqlite3|argparse|threading|subprocess|urllib|concurrent|pathlib|datetime)\b", stripped):
                if "(" in stripped and ")" not in stripped:
                    in_multiline_skip = True
                continue

            # Skip top-level win32 reconfigure in config.py
            if rel_path == "config.py":
                if stripped == 'if sys.platform == "win32":':
                    in_win_reconfig = True
                    continue
                if in_win_reconfig:
                    if stripped.startswith("__version__") or stripped.startswith("#"):
                        in_win_reconfig = False
                    else:
                        continue

            # Skip trailing 'if __name__ == "__main__": main()' inside individual files
            if stripped == 'if __name__ == "__main__":':
                continue
            if stripped == "main()" and idx > 0 and 'if __name__ == "__main__":' in lines[idx - 1]:
                continue

            filtered_lines.append(line)

        mod_name = rel_path.replace("/", ".").replace("\\", ".").replace(".py", "")
        chunk_header = f"\n# =====================================================================\n# SECTION: skillsdb.{mod_name}\n# =====================================================================\n"
        bundled_chunks.append(chunk_header + "\n".join(filtered_lines).strip())

    # Add final entrypoint execution
    entrypoint = """
# =====================================================================
# Standalone CLI Entrypoint
# =====================================================================
if __name__ == "__main__":
    main()
"""
    bundled_chunks.append(entrypoint.strip())

    final_content = "\n\n".join(bundled_chunks) + "\n"

    # Syntax validation before saving
    try:
        compile(final_content, "db_manager.py", "exec")
        print("  * Syntax validation: PASSED")
    except SyntaxError as e:
        print(f"  * Syntax validation FAILED at line {e.lineno}: {e.msg}")
        sys.exit(1)

    target_file.parent.mkdir(parents=True, exist_ok=True)
    target_file.write_text(final_content, encoding="utf-8")
    print(f"\n[OK] Successfully compiled {len(MODULE_ORDER)} modules into:\n{target_file}")
    print(f"Total lines: {len(final_content.splitlines())} lines (~{len(final_content) // 1024} KB)")


if __name__ == "__main__":
    bundle()
